import { Router, type ErrorRequestHandler, type RequestHandler } from "express";
import multer from "multer";
import { isValidObjectId } from "mongoose";
import { requireAuth } from "../middleware/auth";
import { validateContactMessage, validateResource } from "../middleware/validation";
import { ContactMessageModel, ContactMethodModel, ExperienceModel, HeroModel, LanguageModel, ProfileModel, ProjectModel, ResumeModel, ServiceModel, TechnologyModel } from "../models/content.model";
import { storageProvider } from "../services/storage.service";
import { HttpError, isLocalizedString, parseBoolean, parseListQuery } from "../utils/http";

const publicRouter = Router();
const adminRouter = Router();
adminRouter.use(requireAuth);
const publicFilter = { isVisible: true };

const resources: Array<{ path: string; key: "experience" | "service" | "technology" | "language" | "project" | "contactMethod"; model: any; search: string[] }> = [
  { path: "experiences", key: "experience", model: ExperienceModel, search: ["company", "role.fa", "role.en"] },
  { path: "services", key: "service", model: ServiceModel, search: ["title.fa", "title.en"] },
  { path: "technologies", key: "technology", model: TechnologyModel, search: ["name.fa", "name.en", "category"] },
  { path: "languages", key: "language", model: LanguageModel, search: ["name.fa", "name.en", "level.fa", "level.en"] },
  { path: "projects", key: "project", model: ProjectModel, search: ["title.fa", "title.en", "slug"] },
  { path: "contact-methods", key: "contactMethod", model: ContactMethodModel, search: ["type", "label.fa", "label.en", "value"] },
];
const resourceByPath = Object.fromEntries(resources.map((resource) => [resource.path, resource]));

const imageTypes: Record<string, string> = { "image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp" };
const imageUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: (_req, file, callback) => callback(null, Boolean(imageTypes[file.mimetype] && /^\.(jpe?g|png|webp|svg)$/i.test(require("node:path").extname(file.originalname)) )) });
const pdfUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (_req, file, callback) => callback(null, file.mimetype === "application/pdf" && require("node:path").extname(file.originalname).toLowerCase() === ".pdf") });
const handleUploadError: any = (error: any, _req: any, _res: any, next: any) => { if (error instanceof multer.MulterError || error?.message === "Unexpected field") { next(new HttpError(400, error.code === "LIMIT_FILE_SIZE" ? "File exceeds the size limit" : "Invalid upload")); return; } next(error); };

const assertFileSignature = (file: Express.Multer.File) => { const b = file.buffer; const isPng = file.mimetype === "image/png" && b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])); const isJpeg = file.mimetype === "image/jpeg" && b.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff])); const isWebp = file.mimetype === "image/webp" && b.subarray(0, 4).toString() === "RIFF" && b.subarray(8, 12).toString() === "WEBP"; const isPdf = file.mimetype === "application/pdf" && b.subarray(0, 5).toString() === "%PDF-"; if (!isPng && !isJpeg && !isWebp && !isPdf) throw new HttpError(400, "File content does not match its declared type"); };
const saveUploaded = async (file: Express.Multer.File, types: Record<string, string>) => { assertFileSignature(file); return storageProvider.save({ filename: "upload", mimeType: file.mimetype, data: file.buffer, extension: types[file.mimetype] }); };
const parseAlt = (value: unknown) => { if (value === undefined) return undefined; const parsed = typeof value === "string" ? JSON.parse(value) : value; if (!isLocalizedString(parsed)) throw new HttpError(400, "alt must contain fa and en strings"); return parsed; };
const validId = (id: unknown, label = "resource") => { const value = String(id); if (!isValidObjectId(value)) throw new HttpError(400, `Invalid ${label} id`); };
const replaceMedia = async (oldMedia: any, newMedia: any) => { if (oldMedia?.key && oldMedia.key !== newMedia.key) await storageProvider.remove(oldMedia.key); };

const messageRate = new Map<string, { count: number; resetAt: number }>();
const contactRateLimit: RequestHandler = (req, _res, next) => { const now = Date.now(); const key = req.ip ?? "unknown"; const current = messageRate.get(key); if (!current || current.resetAt <= now) messageRate.set(key, { count: 1, resetAt: now + 15 * 60_000 }); else if (current.count >= 10) { next(new HttpError(429, "Too many contact messages; try again later")); return; } else current.count += 1; next(); };

publicRouter.get("/portfolio", async (_req, res, next) => { try { const [hero, profile, experiences, services, technologies, languages, projects, resume, contactMethods] = await Promise.all([HeroModel.findOne({ key: "default", ...publicFilter }).select("-key -createdAt -updatedAt").lean(), ProfileModel.findOne({ key: "default" }).select("-key -createdAt -updatedAt").lean(), ExperienceModel.find(publicFilter).sort({ order: 1, startDate: -1 }).select("-createdAt -updatedAt").lean(), ServiceModel.find(publicFilter).sort({ order: 1 }).select("-createdAt -updatedAt").lean(), TechnologyModel.find(publicFilter).sort({ order: 1 }).select("-createdAt -updatedAt").lean(), LanguageModel.find(publicFilter).sort({ order: 1 }).select("-createdAt -updatedAt").lean(), ProjectModel.find(publicFilter).sort({ featured: -1, order: 1 }).select("-createdAt -updatedAt").lean(), ResumeModel.findOne({ key: "default" }).select("-key -updatedBy -createdAt -updatedAt").lean(), ContactMethodModel.find(publicFilter).sort({ order: 1 }).select("-createdAt -updatedAt").lean()]); res.json({ success: true, data: { hero, profile, experiences, services, technologies, languages, projects, resume, contactMethods } }); } catch (error) { next(error); } });

const publicList = (resource: typeof resources[number]): RequestHandler => async (req, res, next) => { try { const query = parseListQuery(req.query as Record<string, unknown>); const filter: Record<string, unknown> = { ...publicFilter }; if (query.search) filter.$or = resource.search.map((field) => ({ [field]: new RegExp(query.search!, "i") })); const items = await resource.model.find(filter).sort({ [query.sort]: query.order }).skip((query.page - 1) * query.limit).limit(query.limit).select("-createdAt -updatedAt").lean(); res.json({ success: true, data: items }); } catch (error) { next(error); } };
publicRouter.get("/hero", async (_req, res, next) => { try { res.json({ success: true, data: await HeroModel.findOne({ key: "default", ...publicFilter }).select("-key -createdAt -updatedAt").lean() }); } catch (error) { next(error); } });
publicRouter.get("/profile", async (_req, res, next) => { try { res.json({ success: true, data: await ProfileModel.findOne({ key: "default" }).select("-key -createdAt -updatedAt").lean() }); } catch (error) { next(error); } });
for (const resource of resources) publicRouter.get(`/${resource.path}`, publicList(resource));
publicRouter.get("/resume", async (_req, res, next) => { try { res.json({ success: true, data: await ResumeModel.findOne({ key: "default" }).select("-key -updatedBy -createdAt -updatedAt").lean() }); } catch (error) { next(error); } });
publicRouter.post("/contact-messages", contactRateLimit, validateContactMessage, async (req, res, next) => { try { const item = await ContactMessageModel.create(req.body); res.status(201).json({ success: true, data: { id: item._id.toString() } }); } catch (error) { next(error); } });

const singleton = (name: "hero" | "profile" | "resume", model: any, resource: "hero" | "profile" | "resume") => { adminRouter.get(`/${name}`, async (_req, res, next) => { try { res.json({ success: true, data: await model.findOne({ key: "default" }).lean() }); } catch (error) { next(error); } }); adminRouter.put(`/${name}`, validateResource(resource), async (req, res, next) => { try { const item = await model.findOneAndUpdate({ key: "default" }, { $set: req.body, $setOnInsert: { key: "default" } }, { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true }).lean(); res.json({ success: true, data: item }); } catch (error) { next(error); } }); };
singleton("hero", HeroModel, "hero"); singleton("profile", ProfileModel, "profile"); singleton("resume", ResumeModel, "resume");

for (const resource of resources) {
  adminRouter.get(`/${resource.path}`, async (req, res, next) => { try { const query = parseListQuery(req.query as Record<string, unknown>); const filter: Record<string, unknown> = {}; if (query.visible !== undefined) filter.isVisible = query.visible; if (query.search) filter.$or = resource.search.map((field) => ({ [field]: new RegExp(query.search!, "i") })); const [items, total] = await Promise.all([resource.model.find(filter).sort({ [query.sort]: query.order }).skip((query.page - 1) * query.limit).limit(query.limit).lean(), resource.model.countDocuments(filter)]); res.json({ success: true, data: items, meta: { page: query.page, limit: query.limit, total, pages: Math.ceil(total / query.limit) } }); } catch (error) { next(error); } });
  adminRouter.post(`/${resource.path}`, validateResource(resource.key), async (req, res, next) => { try { const item = await resource.model.create(req.body); res.status(201).json({ success: true, data: item }); } catch (error) { next(error); } });
  adminRouter.get(`/${resource.path}/:id`, async (req, res, next) => { try { validId(req.params.id); const item = await resource.model.findById(req.params.id).lean(); if (!item) throw new HttpError(404, "Resource not found"); res.json({ success: true, data: item }); } catch (error) { next(error); } });
  adminRouter.patch(`/${resource.path}/:id`, validateResource(resource.key, true), async (req, res, next) => { try { validId(req.params.id); const item = await resource.model.findByIdAndUpdate(req.params.id, { $set: req.body }, { returnDocument: "after", runValidators: true }).lean(); if (!item) throw new HttpError(404, "Resource not found"); res.json({ success: true, data: item }); } catch (error) { next(error); } });
  adminRouter.delete(`/${resource.path}/:id`, async (req, res, next) => { try { validId(req.params.id); const item = await resource.model.findByIdAndDelete(req.params.id); if (!item) throw new HttpError(404, "Resource not found"); if (resource.key === "project" && item.images) for (const image of item.images) if (image.key) await storageProvider.remove(image.key); res.json({ success: true, message: "Resource deleted" }); } catch (error) { next(error); } });
}

adminRouter.post("/hero/image", imageUpload.single("file"), handleUploadError, async (req, res, next) => { try { if (!req.file) throw new HttpError(400, "An image file is required"); const hero = await HeroModel.findOne({ key: "default" }); if (!hero) throw new HttpError(404, "Hero must be initialized before uploading an image"); const saved = await saveUploaded(req.file, imageTypes); const image = { url: saved.url, key: saved.key, alt: parseAlt(req.body.alt) }; const old = hero.image; hero.image = image as any; await hero.save(); await replaceMedia(old, image); res.status(201).json({ success: true, data: hero.image }); } catch (error) { next(error); } });
adminRouter.patch("/hero/image", async (req, res, next) => { try { const hero = await HeroModel.findOne({ key: "default" }); if (!hero?.image) throw new HttpError(404, "Hero image not found"); hero.image.alt = parseAlt(req.body.alt) as any; await hero.save(); res.json({ success: true, data: hero.image }); } catch (error) { next(error); } });
adminRouter.delete("/hero/image", async (_req, res, next) => { try { const hero = await HeroModel.findOne({ key: "default" }); if (!hero?.image) throw new HttpError(404, "Hero image not found"); const old = hero.image; hero.image = null as any; await hero.save(); if (old.key) await storageProvider.remove(old.key); res.json({ success: true, data: hero }); } catch (error) { next(error); } });

adminRouter.post("/profile/image", imageUpload.single("file"), handleUploadError, async (req, res, next) => { try { if (!req.file) throw new HttpError(400, "An image file is required"); const profile = await ProfileModel.findOne({ key: "default" }); if (!profile) throw new HttpError(404, "Profile must be initialized before uploading an image"); const saved = await saveUploaded(req.file, imageTypes); const image = { url: saved.url, key: saved.key, alt: parseAlt(req.body.alt) }; const old = profile.image; profile.image = image as any; await profile.save(); await replaceMedia(old, image); res.status(201).json({ success: true, data: profile.image }); } catch (error) { next(error); } });

const project = () => ProjectModel;
adminRouter.post("/projects/:id/images", imageUpload.single("file"), handleUploadError, async (req, res, next) => { try { validId(req.params.id, "project"); if (!req.file) throw new HttpError(400, "An image file is required"); const item = await project().findById(req.params.id); if (!item) throw new HttpError(404, "Project not found"); const saved = await saveUploaded(req.file, imageTypes); item.images.push({ url: saved.url, key: saved.key, alt: parseAlt(req.body.alt) } as any); await item.save(); res.status(201).json({ success: true, data: item.images[item.images.length - 1] }); } catch (error) { next(error); } });
adminRouter.patch("/projects/:id/images/:key", async (req, res, next) => { try { validId(req.params.id, "project"); const item = await project().findById(req.params.id); if (!item) throw new HttpError(404, "Project not found"); const image = item.images.find((candidate: any) => candidate.key === req.params.key); if (!image) throw new HttpError(404, "Project image not found"); image.alt = parseAlt(req.body.alt) as any; await item.save(); res.json({ success: true, data: image }); } catch (error) { next(error); } });
adminRouter.delete("/projects/:id/images/:key", async (req, res, next) => { try { validId(req.params.id, "project"); const item = await project().findById(req.params.id); if (!item) throw new HttpError(404, "Project not found"); const index = item.images.findIndex((candidate: any) => candidate.key === req.params.key); if (index < 0) throw new HttpError(404, "Project image not found"); const [image] = item.images.splice(index, 1); await item.save(); if (image.key) await storageProvider.remove(image.key); res.json({ success: true, data: item.images }); } catch (error) { next(error); } });

adminRouter.post("/resume/file", pdfUpload.single("file"), handleUploadError, async (req, res, next) => { try { if (!req.file) throw new HttpError(400, "A PDF file is required"); const resume = await ResumeModel.findOne({ key: "default" }) ?? new ResumeModel({ key: "default" }); const saved = await saveUploaded(req.file, { "application/pdf": ".pdf" }); const old = resume.file; resume.file = { url: saved.url, key: saved.key, alt: undefined } as any; if (req.body.title !== undefined) resume.title = parseAlt(req.body.title) as any; await resume.save(); await replaceMedia(old, resume.file); res.status(201).json({ success: true, data: resume }); } catch (error) { next(error); } });
adminRouter.delete("/resume/file", async (_req, res, next) => { try { const resume = await ResumeModel.findOne({ key: "default" }); if (!resume?.file) throw new HttpError(404, "Resume file not found"); const old = resume.file; resume.file = null as any; await resume.save(); if (old.key) await storageProvider.remove(old.key); res.json({ success: true, data: resume }); } catch (error) { next(error); } });

const messagePath = "/contact-messages";
const registerMessageRoutes = (base: string) => { adminRouter.get(base, async (req, res, next) => { try { const filter: Record<string, string> = {}; if (req.query.status) filter.status = String(req.query.status); const items = await ContactMessageModel.find(filter).sort({ createdAt: -1 }).lean(); res.json({ success: true, data: items }); } catch (error) { next(error); } }); adminRouter.get(`${base}/:id`, async (req, res, next) => { try { validId(req.params.id, "message"); const item = await ContactMessageModel.findById(req.params.id).lean(); if (!item) throw new HttpError(404, "Message not found"); res.json({ success: true, data: item }); } catch (error) { next(error); } }); adminRouter.patch(`${base}/:id`, async (req, res, next) => { try { validId(req.params.id, "message"); const allowed = ["status"]; const update = Object.fromEntries(allowed.filter((key) => Object.prototype.hasOwnProperty.call(req.body, key)).map((key) => [key, req.body[key]])); if (update.status && !["new", "read", "replied", "archived"].includes(update.status)) throw new HttpError(400, "Invalid message status"); if (update.status && update.status !== "new") update.readAt = new Date(); const item = await ContactMessageModel.findByIdAndUpdate(req.params.id, { $set: update }, { new: true, runValidators: true }).lean(); if (!item) throw new HttpError(404, "Message not found"); res.json({ success: true, data: item }); } catch (error) { next(error); } }); adminRouter.delete(`${base}/:id`, async (req, res, next) => { try { validId(req.params.id, "message"); const item = await ContactMessageModel.findByIdAndDelete(req.params.id); if (!item) throw new HttpError(404, "Message not found"); res.json({ success: true, message: "Message deleted" }); } catch (error) { next(error); } }); };
registerMessageRoutes(messagePath); registerMessageRoutes("/messages");

export { publicRouter, adminRouter };
